### ISSUE TITLE
Figaro not loading up correctly

### ISSUE THREAD

**Issue by rizalmuthi** [laserlemon/figaro#195]
Hi, this is super awesome gem

anyway, i have problem with it.
So I have this rails project and I use figaro the manage the ENV
I have this kind of setup:
```
test:
  APP_URL: 'http://localhost:3000'
  notification_minutes: "30"
production:
  APP_URL: ''
  notification_minutes: "30"
development:
  APP_URL: http://localhost:3000
  notification_minutes: "30"
```
The problem is, whenever I add new key, and I try to use `rails c`  and ENV['new_key'] it always returns me nil.
I dont know why, and sometimes I changed the value of the key, but it stills using the OLD value..

Anyhow could I fix this?

Thanks
