### ISSUE TITLE
failing with test: 

### ISSUE THREAD

**Issue by chrishough** [laserlemon/figaro#22]
I am trying to use figaro and cannot seem to figure out why this would blow up:

```
development:
  HELLO: "developers"
test:
  HELLO: "testers"
production:
  HELLO: "users"
```

Using ruby-1.9.3-p327
