### ISSUE TITLE
Version 1.1.1 did not work for me

### ISSUE THREAD

**Issue by Hasna1** [laserlemon/figaro#241]
Hey Guys!

I encountered with an issue today with figaro. I have `config/application.yml` like
```yml
development:
  user_name: bloggingwebsite
  password: 'mypassword'
```

and in `Gemfile` I had
```ruby
group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
  gem 'figaro'
end
```
Then it installed the version `1.1.1`. When I tried to access the `ENV['user_name']` it returned `nil`.

To fix this I had to fix my version to `1.0.0` explicitly.
Now its fixed..

So could you please find out what the problem is?

Thanks!
