### ISSUE TITLE
Feature request: ability to override RAILS_ENV for figaro only

### ISSUE THREAD

**Issue by marienfressinaud** [laserlemon/figaro#244]
Hi,

we have two very similar instances of our application (staging and production) which are both based on the `production` environment.

Problem is we have to set different env variables for these two instances. As explain in https://devcenter.heroku.com/articles/deploying-to-a-custom-rails-environment, it is not recommended to create a `staging` environment since we want to keep production and staging environments as close as possible and it adds complexity.

My suggestion would be to consider an additional env variable such as `FIGARO_ENV` for the `application.yml` file so we can have:

```yml
production:
  S3_BUCKET: 'my-bucket-production'

staging:
  S3_BUCKET: 'my-bucket-staging'
```

But only one Rails environment. What do you think about this?
