### ISSUE TITLE
Using a hash for env value

### ISSUE THREAD

**Issue by btoone** [laserlemon/figaro#40]
I wanted to create something like the following but wasn't able to. 

``` yaml
ADMINS:
 admin1:
   - name
   - password
 admin2:
   - name
   - password
```

It looks like Figaro ignores hashes other than the Rails.env key. Is there a better way to accomplish this with Figaro? I've settled on just flattening the values for now.

``` yaml
NUM_OF_ADMINS: 2
ADMIN_1_NAME:
ADMIN_1_PASSWORD:
ADMIN_2_NAME:
ADMIN_2_PASSWORD:
```

Having a data structure would make it easier for me to seed admins since I could just iterate over the elem/keypairs. Instead I have to explicitly state the number of admins to create and my iteration code isn't very pretty.
