### ISSUE TITLE
Environments can only be declared once

### ISSUE THREAD

**Issue by hrp** [laserlemon/figaro#41]
This will work

```
HELLO: world
development:
  HELLO: developers
  GOODBYE: haters
production:
  HELLO: users
```

This won't

```
HELLO: world
development:
  HELLO: developers
production:
  HELLO: users
development:
  GOODBYE: haters
```

The second `development` block will overwrite the previous one. Depending on intended behavior, augment the docs or fix the bug? (Sorry to be terse... just spent a while fighting this!)
