### ISSUE TITLE
Not parsing config/application.yml correctly

### ISSUE THREAD

**Issue by mtrisoline** [laserlemon/figaro#55]
The rake task doesn't parse the application.yml correctly. It is not following the YAML syntax. It finds variables that are not indentd, but ones that follows the YAML syntax it doesn't find.

EX:

``` yaml

ADMIN_NAME: foo
ADMIN_EMAIL: foo@example.com

development:
  SOME_VAR: 0.0.0.0
  DATABASE_URL: mongo://localhost:27628/dev-database
```

when running `RAILS_ENV=development rake figaro:heroku` it will push the ADMIN_NAME and ADMIN_EMAIL to heroku but not the ones specified under development. Is this a bug or do I have something wrong in my configuration somewhere?
