### ISSUE TITLE
Variables set inside application.yml are not accessible from database.yml

### ISSUE THREAD

**Issue by scaryguy** [laserlemon/figaro#70]
Is this the case or am I missing something?

See my `application.yml`  :

``` yaml
development:
  AWS_BUCKET: xxx
  AWS_ACCESS_KEY_ID: xxx
  AWS_SECRET_ACCESS_KEY: xxx
  DEV_DB_NAME: xxx
  DEV_DB_USERNAME: 'xx'
  DEV_DB_PASSWORD: "'xxx'"
test:
  TEST_DB_NAME: xxx
  TEST_DB_USERNAME: 'xx'
  TEST_DB_PASSWORD: "'xxx'"
```

And here is my `database.yml`  :

``` yaml
development:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['DEV_DB_NAME'] %>
  pool: 5
  username: <%= ENV['DEV_DB_USERNAME'] %>
  password: <%= ENV['DEV_DB_PASSWORD'] %>
  template: template0

test:
  adapter: postgresql
  encoding: unicode
  database:  <%= ENV['TEST_DB_NAME'] %>
  pool: 5
  username: <%= ENV['TEST_DB_USERNAME'] %>
  password:  <%= ENV['TEST_DB_PASSWORD'] %>
  template: template0
```

Eventhough all ENV variables set inside application.yml are accessible from console or whole application, they don't work in two cases:
1. `rails db` : It does not connect to DB because can't read ENV variables.
2. In the test environment. When I try to run my tests, test DB is not accessible due to no password.
