### ISSUE TITLE
Unexpected behavior with environment-specific configuration

### ISSUE THREAD

**Issue by hspinks** [laserlemon/figaro#83]
First of all, thanks for this awesome tool - I can't imagine trying to maintain my config across many environments without it.

However, I did notice recently that my config variables were not pushing correctly according to their environments. I am using the syntax described [here](https://github.com/laserlemon/figaro#give-me-an-example):

``` yaml
# Facebook app ID and secret
FACEBOOK_APP_ID: <development-app-id>
production:
  FACEBOOK_APP_ID: <production-app-id>

FACEBOOK_SECRET: <development-app-secret>
production:
  FACEBOOK_SECRET: <production-app-secret>
```

After running `rake figaro:heroku[my-app-name]`, then checking the config with `heroku config -a my-app-name`, I see the following env variables set:

``` yaml
FACEBOOK_APP_ID: <development-app-id>
FACEBOOK_SECRET: <production-app-secret>
RACK_ENV: production
RAILS_ENV: production
```

Although the syntax is the same for each, it is taking my development app id and my production app secret. I looked at #35 #28 and #7 and I have both `RAILS_ENV` and `RACK_ENV` set to `production` on Heroku. I'm not sure if I am missing something or if I've uncovered a bug here. Any ideas?
