### ISSUE TITLE
i18n with Figaro

### ISSUE THREAD

**Issue by bcackerman** [laserlemon/figaro#87]
Am I able to separate locale's in my `application.yml` file like this?  It doesn't seem to be working.

``` yml
en:
  development:
    FACEBOOK_APP_ID:
en-JM:
  development:
    FACEBOOK_APP_ID:
```
